(cl:in-package window_node-msg)
(cl:export '(DATA-VAL
          DATA
          VMIN-VAL
          VMIN
          VMAX-VAL
          VMAX
          SMIN-VAL
          SMIN
          EROSION_ELEMENT-VAL
          EROSION_ELEMENT
          EROSION_KERNEL-VAL
          EROSION_KERNEL
          DILATION_ELEMENT-VAL
          DILATION_ELEMENT
          DILATION_KERNEL-VAL
          DILATION_KERNEL
          MODE-VAL
          MODE
          HIST_17-VAL
          HIST_17
          HIST_18-VAL
          HIST_18
          HIST_19-VAL
          HIST_19
          HIST_20-VAL
          HIST_20
          HIST_21-VAL
          HIST_21
          HIST_22-VAL
          HIST_22
          SWICH-VAL
          SWICH
          RST-VAL
          RST
))