// Generated by gencpp from file window_node/WinDetMsg.msg
// DO NOT EDIT!


#ifndef WINDOW_NODE_MESSAGE_WINDETMSG_H
#define WINDOW_NODE_MESSAGE_WINDETMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace window_node
{
template <class ContainerAllocator>
struct WinDetMsg_
{
  typedef WinDetMsg_<ContainerAllocator> Type;

  WinDetMsg_()
    : delta_x(0)
    , delta_y(0)
    , scale(0)
    , status(0)  {
    }
  WinDetMsg_(const ContainerAllocator& _alloc)
    : delta_x(0)
    , delta_y(0)
    , scale(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef int16_t _delta_x_type;
  _delta_x_type delta_x;

   typedef int16_t _delta_y_type;
  _delta_y_type delta_y;

   typedef int16_t _scale_type;
  _scale_type scale;

   typedef int16_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::window_node::WinDetMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::window_node::WinDetMsg_<ContainerAllocator> const> ConstPtr;

}; // struct WinDetMsg_

typedef ::window_node::WinDetMsg_<std::allocator<void> > WinDetMsg;

typedef boost::shared_ptr< ::window_node::WinDetMsg > WinDetMsgPtr;
typedef boost::shared_ptr< ::window_node::WinDetMsg const> WinDetMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::window_node::WinDetMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::window_node::WinDetMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace window_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'window_node': ['/home/hossein/catkin_ws/src/window_node/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::window_node::WinDetMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::window_node::WinDetMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::window_node::WinDetMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::window_node::WinDetMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::window_node::WinDetMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::window_node::WinDetMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::window_node::WinDetMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a02cd86d2806c52a7dced0d3efb6c2dd";
  }

  static const char* value(const ::window_node::WinDetMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa02cd86d2806c52aULL;
  static const uint64_t static_value2 = 0x7dced0d3efb6c2ddULL;
};

template<class ContainerAllocator>
struct DataType< ::window_node::WinDetMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "window_node/WinDetMsg";
  }

  static const char* value(const ::window_node::WinDetMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::window_node::WinDetMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 delta_x\n\
int16 delta_y\n\
int16 scale\n\
int16 status\n\
";
  }

  static const char* value(const ::window_node::WinDetMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::window_node::WinDetMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta_x);
      stream.next(m.delta_y);
      stream.next(m.scale);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WinDetMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::window_node::WinDetMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::window_node::WinDetMsg_<ContainerAllocator>& v)
  {
    s << indent << "delta_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.delta_x);
    s << indent << "delta_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.delta_y);
    s << indent << "scale: ";
    Printer<int16_t>::stream(s, indent + "  ", v.scale);
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WINDOW_NODE_MESSAGE_WINDETMSG_H
