(cl:defpackage state_estimator-msg
  (:use )
  (:export
   "<ARDRONE3PILOTINGSTATEATTITUDECHANGED>"
   "ARDRONE3PILOTINGSTATEATTITUDECHANGED"
   "<ARDRONE3PILOTINGSTATESPEEDCHANGED>"
   "ARDRONE3PILOTINGSTATESPEEDCHANGED"
  ))

